import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const UPSTREAM_REPOSITORY = "siboehm/SGEMM_CUDA";
const UPSTREAM_COMMIT = "5a7dcc513d951ba764d51bc9d587b3163f3a894d";
const GENERATED_MODULE_PATH = "src/blog/stochastic-agentic-ascent/data.generated.mjs";
const UPSTREAM_DIRECTORY = "scripts/blog/stochastic-agentic-ascent/upstream";
const MANIFEST_PATH = `${UPSTREAM_DIRECTORY}/manifest.json`;

const KERNEL_SPECS = [
  {
    kernel: "1",
    title: "Naive",
    gflops: 309.0,
    percentOfCublas: 1.3,
    filename: "1_naive.cuh",
    functionName: "sgemm_naive",
  },
  {
    kernel: "2",
    title: "GMEM Coalescing",
    gflops: 1986.5,
    percentOfCublas: 8.5,
    filename: "2_kernel_global_mem_coalesce.cuh",
    functionName: "sgemm_global_mem_coalesce",
  },
  {
    kernel: "3",
    title: "SMEM Caching",
    gflops: 2980.3,
    percentOfCublas: 12.8,
    filename: "3_kernel_shared_mem_blocking.cuh",
    functionName: "sgemm_shared_mem_block",
  },
  {
    kernel: "4",
    title: "1D Blocktiling",
    gflops: 8474.7,
    percentOfCublas: 36.5,
    filename: "4_kernel_1D_blocktiling.cuh",
    functionName: "sgemm1DBlocktiling",
  },
  {
    kernel: "5",
    title: "2D Blocktiling",
    gflops: 15971.7,
    percentOfCublas: 68.7,
    filename: "5_kernel_2D_blocktiling.cuh",
    functionName: "sgemm2DBlocktiling",
  },
  {
    kernel: "6",
    title: "Vectorized Mem Access",
    gflops: 18237.3,
    percentOfCublas: 78.4,
    filename: "6_kernel_vectorize.cuh",
    functionName: "sgemmVectorize",
  },
  {
    kernel: "7",
    title: "Avoid Bank Conflicts (Linearize)",
    gflops: 16213.4,
    percentOfCublas: 69.7,
    filename: "7_kernel_resolve_bank_conflicts.cuh",
    functionName: "sgemmResolveBankConflicts",
  },
  {
    kernel: "8",
    title: "Avoid Bank Conflicts (Offset)",
    gflops: 16459.2,
    percentOfCublas: 70.8,
    filename: "8_kernel_bank_extra_col.cuh",
    functionName: "sgemmResolveBankExtraCol",
  },
  {
    kernel: "9",
    title: "Autotuning",
    gflops: 19721.0,
    percentOfCublas: 84.8,
    filename: "9_kernel_autotuned.cuh",
    functionName: "sgemmAutotuned",
  },
  {
    kernel: "10",
    title: "Warptiling",
    gflops: 21779.3,
    percentOfCublas: 93.7,
    filename: "10_kernel_warptiling.cuh",
    functionName: "sgemmWarptiling",
  },
];

function buildRawSourceUrl(filename) {
  return `https://raw.githubusercontent.com/${UPSTREAM_REPOSITORY}/${UPSTREAM_COMMIT}/src/kernels/${filename}`;
}

function buildBlobSourceUrl(filename) {
  return `https://github.com/${UPSTREAM_REPOSITORY}/blob/${UPSTREAM_COMMIT}/src/kernels/${filename}`;
}

async function downloadText(url) {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`failed to download ${url}: ${response.status} ${response.statusText}`);
  }

  return response.text();
}

function extractKernelFunction(sourceText, functionName) {
  const functionIndex = sourceText.indexOf(`${functionName}(`);
  if (functionIndex === -1) {
    throw new Error(`could not find ${functionName}`);
  }

  const globalIndex = sourceText.lastIndexOf("__global__ void", functionIndex);
  if (globalIndex === -1) {
    throw new Error(`could not find __global__ declaration for ${functionName}`);
  }

  const templateIndex = sourceText.lastIndexOf("template <", globalIndex);
  const startIndex = templateIndex === -1 ? globalIndex : templateIndex;
  const braceStartIndex = sourceText.indexOf("{", functionIndex);
  if (braceStartIndex === -1) {
    throw new Error(`could not find opening brace for ${functionName}`);
  }

  let depth = 0;
  for (let index = braceStartIndex; index < sourceText.length; index += 1) {
    const character = sourceText[index];
    if (character === "{") {
      depth += 1;
      continue;
    }
    if (character === "}") {
      depth -= 1;
      if (depth === 0) {
        return sourceText.slice(startIndex, index + 1);
      }
    }
  }

  throw new Error(`could not find closing brace for ${functionName}`);
}

function stripComments(sourceText) {
  return sourceText
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/\/\/.*$/gm, "");
}

function cleanKernelLines(sourceText) {
  return stripComments(sourceText)
    .replace(/\r/g, "")
    .split("\n")
    .map((line) => line.replace(/[\t ]+$/g, ""))
    .filter((line) => line.trim().length > 0);
}

function createGeneratedModule(generatedStages) {
  return [
    "/*",
    " * This file is auto-generated by `scripts/blog/stochastic-agentic-ascent/update-kernels.mjs`.",
    " * Do not edit it by hand.",
    " */",
    "",
    `export const UPSTREAM_REPOSITORY = ${JSON.stringify(UPSTREAM_REPOSITORY)};`,
    `export const UPSTREAM_COMMIT = ${JSON.stringify(UPSTREAM_COMMIT)};`,
    "",
    `export const GENERATED_KERNEL_STAGES = ${JSON.stringify(generatedStages, null, 2)};`,
    "",
  ].join("\n");
}

function createManifest() {
  return `${JSON.stringify({
    repository: UPSTREAM_REPOSITORY,
    commit: UPSTREAM_COMMIT,
    kernels: KERNEL_SPECS.map((kernelSpec) => {
      return {
        kernel: kernelSpec.kernel,
        filename: kernelSpec.filename,
        functionName: kernelSpec.functionName,
        sourcePath: `src/kernels/${kernelSpec.filename}`,
        sourceUrl: buildBlobSourceUrl(kernelSpec.filename),
      };
    }),
  }, null, 2)}\n`;
}

async function main() {
  const repoRoot = path.resolve(process.cwd());
  const upstreamDirectoryAbsolutePath = path.join(repoRoot, UPSTREAM_DIRECTORY);
  const generatedModuleAbsolutePath = path.join(repoRoot, GENERATED_MODULE_PATH);
  const manifestAbsolutePath = path.join(repoRoot, MANIFEST_PATH);
  const generatedStages = [];

  await mkdir(upstreamDirectoryAbsolutePath, { recursive: true });

  for (const kernelSpec of KERNEL_SPECS) {
    const rawSourceText = await downloadText(buildRawSourceUrl(kernelSpec.filename));
    const vendoredAbsolutePath = path.join(upstreamDirectoryAbsolutePath, kernelSpec.filename);
    await writeFile(vendoredAbsolutePath, rawSourceText, "utf8");

    const kernelSourceText = extractKernelFunction(rawSourceText, kernelSpec.functionName);
    const codeLines = cleanKernelLines(kernelSourceText);
    generatedStages.push({
      kernel: kernelSpec.kernel,
      title: kernelSpec.title,
      gflops: kernelSpec.gflops,
      percentOfCublas: kernelSpec.percentOfCublas,
      sourcePath: `src/kernels/${kernelSpec.filename}`,
      sourceUrl: buildBlobSourceUrl(kernelSpec.filename),
      vendoredPath: `${UPSTREAM_DIRECTORY}/${kernelSpec.filename}`,
      functionName: kernelSpec.functionName,
      cleanedLineCount: codeLines.length,
      codeLines,
    });
  }

  await writeFile(generatedModuleAbsolutePath, createGeneratedModule(generatedStages), "utf8");
  await writeFile(manifestAbsolutePath, createManifest(), "utf8");
}

await main();
